## Project ------------------------------------------------------------

project:
  type: website
  output-dir: _site   # Development folder
#  output-dir: docs   # Production folder

## Website ------------------------------------------------------------

website:
  title: "Management Concepts"
  page-footer:
    center: "Copyright 2026, Bob McQuaid"
  page-navigation: true
  navbar:
    background: "DarkOliveGreen"
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Meetings"
        file: meetings/1mtgs.qmd
      - file: about.qmd

## Format ------------------------------------------------------------

format:
  html:
    theme:
      - Flatly
    css: styles.css
    toc: true

## Editor ------------------------------------------------------------

editor: source



